name       : swaylock
version    : 1.4
release    : 1
source     :
    - https://github.com/swaywm/swaylock/archive/1.4.tar.gz : 8e6ad33d16370084f5242fd19e0ad631deaeb636cd9699cb8561ca9f18751440
license    : MIT
component  : desktop
summary    : swaylock is a screen locking utility for Wayland compositors
description: |
    swaylock is a screen locking utility for Wayland compositors
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
setup      : |
    %meson_configure -Dgdk-pixbuf=enabled -Dpam=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -d $installdir/usr/share/defaults
    mv $installdir/etc $installdir/usr/share/defaults/etc
