name       : swaylock
version    : '1.6'
release    : 4
source     :
    - https://github.com/swaywm/swaylock/archive/refs/tags/1.6.tar.gz : b9181e15d8166bba3a29dabb392cfe94568e4ceb358d388a812cd28c3f61bbe3
license    : MIT
homepage   : https://github.com/swaywm/swaylock
component  : desktop
summary    : swaylock is a screen locking utility for Wayland compositors
description: |
    swaylock is a screen locking utility for Wayland compositors
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
setup      : |
    %meson_configure -Dgdk-pixbuf=enabled -Dpam=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -d $installdir/usr/share/defaults
    mv $installdir/etc $installdir/usr/share/defaults/etc
