name       : swaylock
version    : '1.7'
release    : 5
source     :
    - https://github.com/swaywm/swaylock/archive/refs/tags/1.7.tar.gz : 4c4d3c3ed838c085feb0b237b9aaaabdf66cbc05e2b034b2cb5c552957e620d6
license    : MIT
homepage   : https://github.com/swaywm/swaylock
component  : desktop
summary    : swaylock is a screen locking utility for Wayland compositors
description: |
    swaylock is a screen locking utility for Wayland compositors
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
setup      : |
    %meson_configure -Dgdk-pixbuf=enabled -Dpam=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -d $installdir/usr/share/defaults
    mv $installdir/etc $installdir/usr/share/defaults/etc
